export const LANDING = {
  FOOTER_TAG_LINE: 'FOOTER_TAG_LINE',
  FOOTER_CONTENT_TITLE: 'FOOTER_CONTENT_TITLE',
  FOOTER_CONTENT_HOME: 'FOOTER_CONTENT_HOME',
  FOOTER_CONTENT_FEATURES: 'FOOTER_CONTENT_FEATURES',
  FOOTER_CONTENT_ABOUT_US: 'FOOTER_CONTENT_ABOUT_US',
  FOOTER_CONTENT_SUPPORT: 'FOOTER_CONTENT_SUPPORT',
  FOOTER_CONTENT_CONTACT_US: 'FOOTER_CONTENT_CONTACT_US',
  FOOTER_PARTNERS_TITLE: 'FOOTER_PARTNERS_TITLE',
  FOOTER_SOCIAL_TITLE: 'FOOTER_SOCIAL_TITLE',
  FOOTER_OTHER_TITLE: 'FOOTER_OTHER_TITLE',
};
